---
apiVersion: v1
kind: ConfigMap
metadata:
    name: dov-cm
    namespace: dovns
    labels:
        app: dov
data:
    INSTANCE_NAME: this is from a configmap

---
apiVersion: v1
kind: Secret
metadata:
    name: dov-secret
    namespace: dovns
    labels:
        app: dov
data:
    INSTANCE_HASH: dGhpcyBpcyBteSBlbmNvZGVkIHN0cmluZw==
