---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: bggdb-pvc
    namespace: bggns
    labels:
        app: bgg
spec:
    storageClassName: do-block-storage
    accessModes:
        - ReadWriteOnce
        # - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
