apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - ../../base

namespace: dev-ns
namePrefix: dev-
# labels:
#     - pairs:
#       env: stage

replicas:
    - name: dov-deploy
      count: 1

images:
    - name: chukmunnlee/dov-bear
      newTag: v5
#  CM
# Secrets

