---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dov-deploy
    namespace: myns
    labels:
        apps: dov
spec:
    replicas: 3
    selector:
        matchLabels:
            app: dov
            env: test
    template:
        metadata:
            name: dov-pod
            labels:
                app: dov
                env: test
        spec:
            containers:
                - name: dov-container
                  image: chukmunnlee/dov-bear:v5
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: dov-cm
                      - secretRef:
                            name: dov-secret
                  # env:
                  #     - name: INSTANCE_NAME
                  #       value: "my dov bear"
                  #     - name: INSTANCE_HASH
                  #       valueFrom:
                  #           fieldRef:
                  #               fieldPath: status.podIP
                  ports:
                      - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: dov-svc
    namespace: myns
    labels:
        app: dov
spec:
    type: ClusterIP
    selector:
        app: dov
        env: test
    ports:
        - name: web
          port: 8080
          targetPort: 3000
