## https://docs.docker.com/reference/compose-file/
networks:
  mynet:

volumes:
  myvol:

services:
  appdb:
    image: stackupiss/northwind-db:v1
    networks:
    - mynet
    volumes:
    - myvol:/var/lib/mysql

  app:
    image: stackupiss/northwind-app:v1
    environment:
    - DB_HOST=appdb 
    - DB_USER=root 
    - DB_PASSWORD=changeit 
    ports:
    - 8080:3000
    networks:
    - mynet
    depends_on:
    - appdb