---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: bggapp-deploy
    namespace: bggns
    labels:
        app: bgg
        name: bggapp-deploy
spec:
    replicas: 3
    selector:
        matchLabels:
            app: bgg
            name: bggapp-po
    template:
        metadata:
            name: bggapp-po
            labels:
                app: bgg
                name: bggapp-po
        spec:
            containers:
                - name: bggapp-container
                  image: stackupiss/bgg-backend:v2
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: bgg-cm
                      - secretRef:
                            name: bgg-secret
                  ports:
                      - name: bggapp-port
                        containerPort: 3000
                  readinessProbe:
                      httpGet:
                          path: /healthz
                          port: bggapp-port
                      timeoutSeconds: 5
                      failureThreshold: 1
                  livenessProbe:
                      httpGet:
                          path: /healthz
                          port: bggapp-port
                      timeoutSeconds: 5
                      failureThreshold: 3
                      successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
    name: bggapp-svc
    namespace: bggns
    labels:
        app: bgg
        name: bggapp-svc
spec:
    # type: ClusterIP
    # type: NodePort
    type: LoadBalancer
    selector:
        app: bgg
        name: bggapp-po
    ports:
        - port: 3000 # external
          targetPort: bggapp-port # containerPort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: bggapp-ing
    namespace: bggns
    labels:
        app: bgg
spec:
    ingressClassName: nginx
    rules:
        - host: bgg-139.59.221.43.nip.io
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: bggapp-svc
                            port:
                                name: bggapp-port
