---
apiVersion: v1
kind: Service
metadata:
    name: minio-hsvc
    namespace: minio-ns
spec:
    clusterIP: None
    selector:
        app: minio
        name: minio-po
    ports:
        - name: data
          port: 9000
          targetPort: 9000
        - name: console
          port: 9090
          targetPort: 9090

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: minio-sts
    namespace: minio-ns
spec:
    replicas: 4
    serviceName: minio-hsvc
    selector:
        matchLabels:
            app: minio
            name: minio-po
    volumeClaimTemplates:
        - metadata:
              name: data-vol
          spec:
              accessModes: [ReadWriteOnce]
              storageClassName: do-block-storage
              resources:
                  requests:
                      storage: 1Gi
    template:
        metadata:
            labels:
                app: minio
                name: minio-po
        spec:
            securityContext:
                fsGroup: 1001
            containers:
                - name: minio-container
                  image: bitnami/minio:2024.8.29
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - configMapRef:
                            name: minio-cm
                      - secretRef:
                            name: minio-secret
                  livenessProbe:
                      httpGet:
                          path: /minio/health/live
                          port: 9000
                      initialDelaySeconds: 60
                      periodSeconds: 30
                  ports:
                      - name: data
                        containerPort: 9000
                      - name: console
                        containerPort: 9090
                  volumeMounts:
                      - name: data-vol
                        mountPath: /data
                  resources:
                      requests:
                          memory: 250M
                          cpu: 200m
                      limits:
                          memory: 250M
                          cpu: 200m
                  readinessProbe:
                      httpGet:
                          path: /minio/health/ready
                          port: 9000
                      timeoutSeconds: 5
                      failureThreshold: 1
                  livenessProbe:
                      httpGet:
                          path: /minio/health/live
                          port: 9000
                      timeoutSeconds: 5
                      failureThreshold: 3
                      successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
    name: minio-svc
    namespace: minio-ns
spec:
    type: ClusterIP
    selector:
        app: minio
        name: minio-po
    ports:
        - name: data
          port: 9000
          targetPort: 9000
        - name: console
          port: 9090
          targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: minio-ing
    namespace: minio-ns
    annotations:
        nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
    ingressClassName: nginx
    rules:
        - host: data-139.59.221.43.nip.io
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: minio-svc
                            port:
                                number: 9000
        - host: console-139.59.221.43.nip.io
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: minio-svc
                            port:
                                number: 9090
